version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch
